/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceptionistIndexRouteImport } from './routes/receptionist/index'
import { Route as MarketingIndexRouteImport } from './routes/marketing/index'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as MarketingScrapeRouteImport } from './routes/marketing.scrape'
import { Route as CrmNewRouteImport } from './routes/crm/new'
import { Route as ReceptionistMessagesThreadIdRouteImport } from './routes/receptionist.messages.$threadId'
import { Route as ReceptionistCallsIdRouteImport } from './routes/receptionist.calls.$id'
import { Route as MarketingCampaignsNewRouteImport } from './routes/marketing.campaigns.new'
import { Route as MarketingCampaignsIdRouteImport } from './routes/marketing/campaigns/$id'
import { Route as CrmLeadsIdRouteImport } from './routes/crm.leads.$id'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionistIndexRoute = ReceptionistIndexRouteImport.update({
  id: '/receptionist/',
  path: '/receptionist/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingScrapeRoute = MarketingScrapeRouteImport.update({
  id: '/marketing/scrape',
  path: '/marketing/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmNewRoute = CrmNewRouteImport.update({
  id: '/crm/new',
  path: '/crm/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionistMessagesThreadIdRoute =
  ReceptionistMessagesThreadIdRouteImport.update({
    id: '/receptionist/messages/$threadId',
    path: '/receptionist/messages/$threadId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReceptionistCallsIdRoute = ReceptionistCallsIdRouteImport.update({
  id: '/receptionist/calls/$id',
  path: '/receptionist/calls/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCampaignsNewRoute = MarketingCampaignsNewRouteImport.update({
  id: '/marketing/campaigns/new',
  path: '/marketing/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCampaignsIdRoute = MarketingCampaignsIdRouteImport.update({
  id: '/marketing/campaigns/$id',
  path: '/marketing/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsIdRoute = CrmLeadsIdRouteImport.update({
  id: '/crm/leads/$id',
  path: '/crm/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/deck': typeof DeckRoute
  '/login': typeof LoginRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/social': typeof SocialRoute
  '/crm/new': typeof CrmNewRoute
  '/marketing/scrape': typeof MarketingScrapeRoute
  '/crm/': typeof CrmIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/receptionist/': typeof ReceptionistIndexRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/marketing/campaigns/$id': typeof MarketingCampaignsIdRoute
  '/marketing/campaigns/new': typeof MarketingCampaignsNewRoute
  '/receptionist/calls/$id': typeof ReceptionistCallsIdRoute
  '/receptionist/messages/$threadId': typeof ReceptionistMessagesThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/deck': typeof DeckRoute
  '/login': typeof LoginRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/social': typeof SocialRoute
  '/crm/new': typeof CrmNewRoute
  '/marketing/scrape': typeof MarketingScrapeRoute
  '/crm': typeof CrmIndexRoute
  '/marketing': typeof MarketingIndexRoute
  '/receptionist': typeof ReceptionistIndexRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/marketing/campaigns/$id': typeof MarketingCampaignsIdRoute
  '/marketing/campaigns/new': typeof MarketingCampaignsNewRoute
  '/receptionist/calls/$id': typeof ReceptionistCallsIdRoute
  '/receptionist/messages/$threadId': typeof ReceptionistMessagesThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/deck': typeof DeckRoute
  '/login': typeof LoginRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/social': typeof SocialRoute
  '/crm/new': typeof CrmNewRoute
  '/marketing/scrape': typeof MarketingScrapeRoute
  '/crm/': typeof CrmIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/receptionist/': typeof ReceptionistIndexRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/marketing/campaigns/$id': typeof MarketingCampaignsIdRoute
  '/marketing/campaigns/new': typeof MarketingCampaignsNewRoute
  '/receptionist/calls/$id': typeof ReceptionistCallsIdRoute
  '/receptionist/messages/$threadId': typeof ReceptionistMessagesThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/contact'
    | '/deck'
    | '/login'
    | '/request-quote'
    | '/services'
    | '/social'
    | '/crm/new'
    | '/marketing/scrape'
    | '/crm/'
    | '/marketing/'
    | '/receptionist/'
    | '/crm/leads/$id'
    | '/marketing/campaigns/$id'
    | '/marketing/campaigns/new'
    | '/receptionist/calls/$id'
    | '/receptionist/messages/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/contact'
    | '/deck'
    | '/login'
    | '/request-quote'
    | '/services'
    | '/social'
    | '/crm/new'
    | '/marketing/scrape'
    | '/crm'
    | '/marketing'
    | '/receptionist'
    | '/crm/leads/$id'
    | '/marketing/campaigns/$id'
    | '/marketing/campaigns/new'
    | '/receptionist/calls/$id'
    | '/receptionist/messages/$threadId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/contact'
    | '/deck'
    | '/login'
    | '/request-quote'
    | '/services'
    | '/social'
    | '/crm/new'
    | '/marketing/scrape'
    | '/crm/'
    | '/marketing/'
    | '/receptionist/'
    | '/crm/leads/$id'
    | '/marketing/campaigns/$id'
    | '/marketing/campaigns/new'
    | '/receptionist/calls/$id'
    | '/receptionist/messages/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ContactRoute: typeof ContactRoute
  DeckRoute: typeof DeckRoute
  LoginRoute: typeof LoginRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  ServicesRoute: typeof ServicesRoute
  SocialRoute: typeof SocialRoute
  CrmNewRoute: typeof CrmNewRoute
  MarketingScrapeRoute: typeof MarketingScrapeRoute
  CrmIndexRoute: typeof CrmIndexRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  ReceptionistIndexRoute: typeof ReceptionistIndexRoute
  CrmLeadsIdRoute: typeof CrmLeadsIdRoute
  MarketingCampaignsIdRoute: typeof MarketingCampaignsIdRoute
  MarketingCampaignsNewRoute: typeof MarketingCampaignsNewRoute
  ReceptionistCallsIdRoute: typeof ReceptionistCallsIdRoute
  ReceptionistMessagesThreadIdRoute: typeof ReceptionistMessagesThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptionist/': {
      id: '/receptionist/'
      path: '/receptionist'
      fullPath: '/receptionist/'
      preLoaderRoute: typeof ReceptionistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/scrape': {
      id: '/marketing/scrape'
      path: '/marketing/scrape'
      fullPath: '/marketing/scrape'
      preLoaderRoute: typeof MarketingScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/new': {
      id: '/crm/new'
      path: '/crm/new'
      fullPath: '/crm/new'
      preLoaderRoute: typeof CrmNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptionist/messages/$threadId': {
      id: '/receptionist/messages/$threadId'
      path: '/receptionist/messages/$threadId'
      fullPath: '/receptionist/messages/$threadId'
      preLoaderRoute: typeof ReceptionistMessagesThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptionist/calls/$id': {
      id: '/receptionist/calls/$id'
      path: '/receptionist/calls/$id'
      fullPath: '/receptionist/calls/$id'
      preLoaderRoute: typeof ReceptionistCallsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/campaigns/new': {
      id: '/marketing/campaigns/new'
      path: '/marketing/campaigns/new'
      fullPath: '/marketing/campaigns/new'
      preLoaderRoute: typeof MarketingCampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/campaigns/$id': {
      id: '/marketing/campaigns/$id'
      path: '/marketing/campaigns/$id'
      fullPath: '/marketing/campaigns/$id'
      preLoaderRoute: typeof MarketingCampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads/$id': {
      id: '/crm/leads/$id'
      path: '/crm/leads/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof CrmLeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  ContactRoute: ContactRoute,
  DeckRoute: DeckRoute,
  LoginRoute: LoginRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  ServicesRoute: ServicesRoute,
  SocialRoute: SocialRoute,
  CrmNewRoute: CrmNewRoute,
  MarketingScrapeRoute: MarketingScrapeRoute,
  CrmIndexRoute: CrmIndexRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  ReceptionistIndexRoute: ReceptionistIndexRoute,
  CrmLeadsIdRoute: CrmLeadsIdRoute,
  MarketingCampaignsIdRoute: MarketingCampaignsIdRoute,
  MarketingCampaignsNewRoute: MarketingCampaignsNewRoute,
  ReceptionistCallsIdRoute: ReceptionistCallsIdRoute,
  ReceptionistMessagesThreadIdRoute: ReceptionistMessagesThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
